name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
     
        # Login ke GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN sudah tersedia secara otomatis dalam Actions

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/mfisya/belajar-cicd:latest .

      # Push Docker image ke GHCR
      - name: Push Docker image
        run: docker push ghcr.io/mfisya/belajar-cicd:latest

      # Run Docker container to check if the application works
      - name: Run Docker container
        run: |
          docker run --name test-container -d ghcr.io/mfisya/belajar-cicd:latest
          sleep 10  # Wait for the container to initialize

      # Check if the Docker container is running successfully
      - name: Check Docker container status
        run: |
          docker ps -q --filter "name=test-container" || exit 1

      - name: Clean up
        run: |
          docker stop test-container
          docker rm test-container
